project:
  type: book

book:
  title: "A quick primer to NextFlow"
  author: 
  - name: Wim Cuypers
    orcid: 0000-0002-1895-3526
    email: wim.cuypers@uantwerpen.be
    affiliations:
      - University of Antwerp
  date: "10/21/2024"
  chapters:
    - content/index.qmd
    - content/intro.qmd
    - content/summary.qmd
    - content/references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



